-- Sample data insertion script for HES-Kaifa Events
-- This script demonstrates how to insert data from JSON files

-- Example: Insert data from the sample JSON file
-- Replace the JSON data with actual data from your JSON files

INSERT INTO hes_events (message_type, timestamp) VALUES 
('EndDeviceEvent', '2025-09-22T11:16:03.757262+00:00');

-- Get the event ID for the inserted record
-- You would typically use the insert_hes_event_from_json function instead

-- Example usage of the JSON insertion function:
/*
SELECT insert_hes_event_from_json('{
  "message_type": "EndDeviceEvent",
  "timestamp": "2025-09-22T11:16:03.757262",
  "header": {
    "verb": "Create",
    "noun": "EndDeviceEvents",
    "revision": "1.0",
    "timestamp": "2025-09-22T11:16:03.682Z",
    "source": "OMS-Traffic-Simulator",
    "async_reply_flag": "false",
    "ack_required": "false",
    "user": {
      "ns1:UserID": "simulator_user",
      "ns1:Organization": "Amman-OMS"
    },
    "message_id": "msg_1758539763682_29",
    "correlation_id": "corr_1758539763682_15",
    "comment": "Generated by OMS Traffic Simulator for Al-Humr"
  },
  "payload": {
    "event_id": "msg_1758539763682_30",
    "created_date_time": "2025-09-22T11:16:03.682Z",
    "issuer_id": "OMS-Simulator",
    "issuer_tracking_id": "msg_1758539763682_29",
    "reason": "Transformer Fault",
    "severity": "High",
    "user_id": "simulator_user",
    "assets": {
      "ns2:mRID": "asset_1758539763682_0",
      "ns2:Names": {
        "ns2:name": "Asset 0",
        "ns2:NameType": {
          "ns2:name": "Asset Name",
          "ns2:description": "Power system asset identifier"
        }
      }
    },
    "event_details": [
      {
        "ns2:name": "Frequency",
        "ns2:value": "50.57Hz"
      },
      {
        "ns2:name": "Power",
        "ns2:value": "501.50kW"
      },
      {
        "ns2:name": "Current",
        "ns2:value": "77.69A"
      },
      {
        "ns2:name": "Voltage",
        "ns2:value": "232.49V"
      }
    ],
    "event_type": {
      "@ref": "PowerOutage"
    },
    "names": {
      "ns2:name": "Event 0",
      "ns2:NameType": {
        "ns2:name": "Event Name",
        "ns2:description": "Power system event identifier"
      }
    },
    "status": {
      "ns2:dateTime": "2025-09-22T11:16:03.682Z",
      "ns2:reason": "Transformer Fault",
      "ns2:remark": "Simulated event for testing purposes",
      "ns2:value": "Active"
    },
    "usage_point": {
      "ns2:mRID": "up_1758539763682_0",
      "ns2:Names": {
        "ns2:name": "Al-Humr",
        "ns2:NameType": {
          "ns2:name": "Usage Point Name",
          "ns2:description": "Power consumption point identifier"
        }
      }
    }
  },
  "metadata": {
    "source": "hes-kaifa-outage-topic",
    "processed_at": "2025-09-22T11:16:03.757470"
  },
  "original_message": {
    "timestamp": "2025-09-22T11:16:03.729517",
    "source": "web2-hes-mock-generator",
    "topic": "hes-kaifa-outage-topic",
    "processed_at": "2025-09-22T11:16:03.729537"
  }
}');
*/
