global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OMS Metrics Collector
  - job_name: 'oms-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 5s
    metrics_path: /metrics

  # Kafka Exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s

  # OMS API (if you add metrics endpoint)
  - job_name: 'oms-api'
    static_configs:
      - targets: ['host.docker.internal:5000']
    scrape_interval: 10s
    metrics_path: /metrics
