global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # APISIX Gateway
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    metrics_path: '/apisix/prometheus/metrics'
    scrape_interval: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Kafka REST Proxy
  - job_name: 'kafka-rest'
    static_configs:
      - targets: ['kafka-rest:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Zookeeper
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 10s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # OMS App Mock (if it exposes metrics)
  - job_name: 'oms-app'
    static_configs:
      - targets: ['oms-app-mock:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # KAIFA HES Mock (if it exposes metrics)
  - job_name: 'kaifa-hes'
    static_configs:
      - targets: ['kaifa-hes-mock:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # etcd
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # OMS Professional Metrics Collector
  - job_name: 'oms-professional-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s